### PR TITLE
improved the add recipe form

### PR DESCRIPTION
**Pull request by rinoma**
Relates #44

### CODE REVIEW

**Comment by Karyum** [comment]
@rinoma this is the last one i check

**Review by tyeung2017 — APPROVED** [review]
we know it is half way done, but we want the change on github

**Comment by Karyum** [comment]
@rinoma you can work later tonight and i might be able to merge tomorrow morning

**Comment by rinoma** [comment]
ok cool

**Review by Karyum — APPROVED** [review]

**Pull request merged**
