### PR TITLE
Links to recipe db

### PR DESCRIPTION
**Pull request by tyeung2017**
relate #38

### CODE REVIEW

**Review by rinoma — APPROVED** [review]
great

**Comment by Karyum** [comment]
@rinoma I'm pretty sure if you actually review this your going to find issues 
**open the files changed and look**

**Comment by Karyum** [comment]
also @tyeung2017 thats a bad name for a PR change it and fix the conflict

**Comment by rinoma** [comment]
@Karyum yes the file wasn't save before committing

**Review by rinoma — APPROVED** [review]
THey work now @Karyum

**Review by Karyum — APPROVED** [review]

**Pull request merged**
