### PR TITLE
Created some dbqueries and modularised the code

### PR DESCRIPTION
**Pull request by rinoma**
Relates #20

### CODE REVIEW

**Comment by rinoma** [comment]
some comment here

**Review by tyeung2017 — APPROVED** [review]
mario approves merge please

**Comment by shiryz** [comment]
@tyeung2017 you guys can start working on something different and unrelated til @Karyum reviews.

**Comment by rinoma** [comment]
@shiryz don't agree. This is hindering our learning outcome. Deadline is tomorrow at 6pm, not today.

**Comment by rinoma** [comment]
since the sprint is only for 1.5days and not 3 weeks

**Comment by rinoma** [comment]
It is not morally correct to text mario to tell him to stop him from approving/merging  pull requests

**Comment by shiryz** [comment]
@rinoma you can still work, there's a difference between writing the code and getting it merged. if you want  clean and correct code you should wait for the QA to approve whether or not you're working on something related

**Comment by shiryz** [comment]
you can always merge this branch to the one you're working on, I never said you should stop working/learning.

**Comment by Karyum** [comment]
@rinoma @shiryz **This will not be a special cohort**.
** every cohort stopped working on 6pm EVEN IF ITS TUSEDAY this cohort will not be different**
# you always have tomorrow and its fine

**Comment by Karyum** [comment]
# you want to work 
**you can always work on another thing and make a PR**
**but they will be reviewed tomorrow**

**Comment by rinoma** [comment]
Sure, but then this should have been clear in the instructions when was the cutoff time for merging was.

**Comment by rinoma** [comment]
it looks like you guys are ot interested in our learning but rather that some petty rules are followed

**Comment by rinoma** [comment]
sometimes all these procedures make it look like the interest should not be on our learning outcome but rather to follow some petty rules

**Review by Karyum — APPROVED** [review]
:+1: please take this seriously you guys

**Pull request merged**
